name: Lint
on: [push]
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        run: |
          npm ci
          npm run lint
